spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate.dialect: org.hibernate.dialect.H2Dialect
        hibernate.format_sql: true
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    org.hibernate:
      SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
    org.hibernate.type.descriptor.sql: ERROR